/** 标准报告入口模板注入：把工程内的块/联动 handler 收敛为 bundle 的两张映射表。 */
import type { ScanResult } from './schema-scan.ts';

/**
 * 生成报告 bundle 的入口源码（注入，不落工程）。导出：
 * - bundle: entry → 块组件（AIBlock 容器据此挂载）
 * - customHandlers: handlerRef → 函数（EventRuntime 据此装配代码联动）
 */
export function generateBundleEntry(scan: ScanResult): string {
  const alias = new Map<string, string>();
  let i = 0;
  const aliasOf = (file: string): string => {
    let a = alias.get(file);
    if (!a) alias.set(file, (a = `M${i++}`));
    return a;
  };
  for (const b of scan.blocks) aliasOf(b.file);
  for (const h of scan.handlers) aliasOf(h.file);

  const imports = [...alias].map(([file, a]) => `import * as ${a} from './${file}';`).join('\n');
  const bundleEntries = scan.blocks
    .map((b) => `  ${JSON.stringify(b.entry)}: ${aliasOf(b.file)}.default,`)
    .join('\n');
  const handlerEntries = scan.handlers
    .map((h) => `  ${JSON.stringify(h.ref)}: ${aliasOf(h.file)}[${JSON.stringify(h.exportName)}],`)
    .join('\n');

  return `// AUTO-GENERATED by @daf/report-scripts — 报告 bundle 入口
${imports}

export const bundle = {
${bundleEntries}
};

export const customHandlers = {
${handlerEntries}
};
`;
}
